# Generated by Django 4.2 on 2023-04-13 13:49

import app.account.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='last_name')),
                ('image', models.ImageField(upload_to=app.account.models.image_path)),
                ('bio', models.TextField()),
                ('role', models.IntegerField(choices=[(0, 'Teacher'), (1, 'Student'), (2, 'Staff')], default=0)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super user')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff user')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active user')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
