# Generated by Django 4.2 on 2023-04-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
